### PR TITLE
Adding Duckduckgoapi for Websearch

### PR DESCRIPTION
**Pull request by GivAlz**
Hi everyone!

Since all SearchAPIs available as default with Haystack are commercial (or with a free trial) I thought it would be a nice idea to add a free API.

Introducing `DuckduckgoApiWebSearch` which uses `Duckduckgo_search` under the hood to make the searches.

The class is essentially a modification of the haystack classes.

Any feedback is welcome. Thank you!

### CODE REVIEW

**Review by anakin87 — COMMENTED** [review]
Very nice idea and component!

Unfortunately, something is not working for me.
I installed the package with `pip install duckduckgo-api-haystack`.

`from duckduckgo_api_haystack import DuckduckgoApiWebSearch`
fails with:
`ModuleNotFoundError: No module named 'duckduckgo_api_haystack'`

Can you take a look and see if something is wrong?

**Comment by GivAlz** [comment]
Thank you for the review @anakin87 ...that  was goofy of me! I changed the package's name at the beginning, I guess this caused the issue.

I just released version 0.1.11, which contains a typo in the Readme but I double checked and the command 

  from duckduckgo_api_haystack import DuckduckgoApiWebSearch

runs properly...plus I added a frequency limiter to avoid limiting rates.

**Comment by anakin87** [comment]
I have tried but I still get a `ModuleNotFoundError`.
See [this notebook](https://colab.research.google.com/drive/1VBBJB3PCzonKky9PZxGCtF7S8o-dpKyT#scrollTo=3_2zcbsArkcb).

There might be some problem with packaging.
Here's a link to an old project of mine, which I hope it can help: https://github.com/anakin87/haystack-entailment-checker.

**Comment by GivAlz** [comment]
I have tried on another machine and now I can reproduce the error, it likely is caused by the use of "-" in the package name (I can see that the package.egg-info didn't track the files correctly).

I'll fix and test on different machines, then let you know...sorry, still new to packaging. And thank you, @anakin87 !

**Comment by GivAlz** [comment]
There was an issue in the `pyproject.toml`, the following part was loading from a non-existent directory

    [tool.setuptools.packages.find]
    include = ["duckduckgo_api_haystack*"] # <--- wrong line was here
    
 I have packaged a new version (v 0.1.12) and tested it locally and from a google colab..sorry again @anakin87 !

**Review by anakin87 — APPROVED** [review]
Now it works like a charm :sparkles:  

I will merge this PR (I felt free to do some cosmetic changes)...

Just a heads-up...
Since you are using this syntax: `str | None`,
your library requires python>=3.10. It would be better to change the pyproject.toml file to reflect this (I got errors with older python versions -> https://stackoverflow.com/questions/76712720/typeerror-unsupported-operand-types-for-type-and-nonetype).

**Comment by GivAlz** [comment]
> Now it works like a charm ✨
> 
> I will merge this PR (I felt free to do some cosmetic changes)...
> 
> Just a heads-up... Since you are using this syntax: `str | None`, your library requires python>=3.10. It would be better to change the pyproject.toml file to reflect this (I got errors with older python versions -> https://stackoverflow.com/questions/76712720/typeerror-unsupported-operand-types-for-type-and-nonetype).

Thank you for the changes and suggestions: I'll fix them in the next package version!!

**Pull request merged**
